/** Declaration file generated by dts-gen */

export = image_downloader;

declare function image_downloader(options: any): any;

declare namespace image_downloader {
    function image(options: any): any;

}

